Repository VerifiedInc/Hooli-Demo-Web, pull requests merged in 2023-08, with the labels that each got.

#38 fix: credential formats
  app/coreAPI.server.ts
Labels: 1 min review, single-line, hotfix

#39 [credentials] updated to use first and last name creds.
  app/coreAPI.server.ts
Labels: 1 min review

#40 feat: add sentry
  .circleci/config.yml
  .env.example
  app/config.client.ts
  app/config.ts
  app/entry.client.tsx
  app/entry.server.tsx
  app/root.tsx
  app/sentry.client.ts
  app/sentry.server.ts
  package-lock.json
  package.json
  server.js
Labels: 30 min review
